# Generated by Django 5.2.1 on 2025-07-04 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0006_patient_diagnosis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atencion",
            name="paciente",
            field=models.ForeignKey(
                help_text="Paciente que recibe esta atención médica (modelo doctor.Patient).",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="atenciones_doctor",
                to="doctor.patient",
                verbose_name="Paciente",
            ),
        ),
    ]
