# Generated by Django 5.2.2 on 2025-07-04 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_alter_atencion_paciente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['apellido', 'primer_nombre'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Primer_nombre',
            new_name='primer_nombre',
        ),
    ]
