# Generated by Django 5.2.2 on 2025-07-04 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_alter_patient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citamedica',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='doctor.patient', verbose_name='Paciente'),
        ),
    ]
