# Generated by Django 5.2.1 on 2025-07-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_alter_audituser_accion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audituser',
            options={'ordering': ['-fecha', '-hora'], 'verbose_name': 'Auditoría de Usuario', 'verbose_name_plural': 'Auditorías de Usuario'},
        ),
        migrations.AddField(
            model_name='audituser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado en'),
        ),
        migrations.AlterField(
            model_name='audituser',
            name='accion',
            field=models.CharField(max_length=50, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='audituser',
            name='estacion',
            field=models.CharField(max_length=50, verbose_name='Estación/IP'),
        ),
        migrations.AlterField(
            model_name='audituser',
            name='registroid',
            field=models.IntegerField(verbose_name='ID Registro'),
        ),
        migrations.AlterModelTable(
            name='audituser',
            table='security_audit_user',
        ),
    ]
